server:
  port: 8088
spring:
  application:
    name: mybatis-plus-demo
  datasource:
    url: jdbc:mysql://localhost:3306/student_mysql?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 30000


logging:
  level:
    com.example: debug


mybatis-plus:
  type-aliases-package: com.example.demo.entity # 别名扫描包
  mapper-locations: classpath*:/mapper/*.xml # mapper的xml文件地址
  global-config:
    db-config:
      id-type: auto # 全局主键策略，默认为自增长
      update-strategy: not_null # 更新时，只更新非null字段
      insert-strategy: not_null # 新增时，只新增非null字段